<!-- ======================================================
     END of <main>
     ====================================================== -->
</main>

<!-- ======================================================
     FOOTER
     ====================================================== -->
<footer class="site-footer mt-auto py-4" role="contentinfo">
    <div class="container">
        <div class="row g-4">

            <div class="col-md-4">
                <h5 class="footer-brand">
                    <i class="bi bi-bag-heart-fill me-1" aria-hidden="true"></i>
                    <?= SITE_NAME ?>
                </h5>
                <p class="text-muted small">Quality products crafted for modern living. Shop with confidence.</p>
            </div>

            <div class="col-md-4">
                <h6 class="footer-heading">Quick Links</h6>
                <ul class="list-unstyled footer-links">
                    <li><a href="<?= SITE_URL ?>/index.php">Home</a></li>
                    <li><a href="<?= SITE_URL ?>/pages/products.php">Products</a></li>
                    <li><a href="<?= SITE_URL ?>/pages/about.php">About Us</a></li>
                    <li><a href="<?= SITE_URL ?>/pages/cart.php">Cart</a></li>
                </ul>
            </div>

            <div class="col-md-4">
                <h6 class="footer-heading">Account</h6>
                <ul class="list-unstyled footer-links">
                    <?php if (isLoggedIn()): ?>
                        <li><a href="<?= SITE_URL ?>/pages/logout.php">Logout</a></li>
                    <?php else: ?>
                        <li><a href="<?= SITE_URL ?>/pages/login.php">Login</a></li>
                        <li><a href="<?= SITE_URL ?>/pages/register.php">Register</a></li>
                    <?php endif; ?>
                </ul>
            </div>
        </div>

        <hr class="footer-divider">
        <p class="text-center text-muted small mb-0">
            &copy; <?= date('Y') ?> <?= SITE_NAME ?>. All rights reserved.
        </p>
    </div>
</footer>


<?php if (defined('ENABLE_GEMINI_CHATBOT') && ENABLE_GEMINI_CHATBOT): ?>
<div id="gemini-chatbot" class="chatbot-shell" aria-live="polite">
    <button id="chatbot-toggle" class="chatbot-toggle" type="button" aria-controls="chatbot-panel" aria-expanded="false">
        <i class="bi bi-chat-dots-fill" aria-hidden="true"></i>
        <span>Tea Assistant</span>
    </button>

    <section id="chatbot-panel" class="chatbot-panel" hidden aria-labelledby="chatbot-title">
        <div class="chatbot-panel-header">
            <div>
                <h2 id="chatbot-title" class="chatbot-title">Tea Assistant</h2>
                <p class="chatbot-subtitle mb-0">Ask about products, recommendations, or help using the store.</p>
            </div>
            <button id="chatbot-close" type="button" class="chatbot-close" aria-label="Close chatbot">
                <i class="bi bi-x-lg" aria-hidden="true"></i>
            </button>
        </div>

        <div id="chatbot-messages" class="chatbot-messages" role="log" aria-live="polite" aria-label="Chat messages">
            <div class="chatbot-message chatbot-message-bot">
                Hello! I'm the Tea Assistant. Ask me about products, recommendations, or where to find something on the site.
            </div>
        </div>

        <form id="chatbot-form" class="chatbot-form">
            <label for="chatbot-input" class="visually-hidden">Type your message</label>
            <textarea id="chatbot-input" class="form-control chatbot-input" rows="2" maxlength="2000" placeholder="Ask Tea Assistant something..."></textarea>
            <div class="chatbot-actions">
                <small class="text-muted">Responses are generated by Gemini.</small>
                <button id="chatbot-send" type="submit" class="btn-store">Send</button>
            </div>
        </form>
    </section>
</div>
<?php endif; ?>

<!-- Toast notification for Add to Cart -->
<div class="position-fixed bottom-0 end-0 p-3" style="z-index: 9999">
    <div id="cart-toast" class="toast align-items-center border-0" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="d-flex">
            <div class="toast-body d-flex align-items-center gap-2">
                <i id="cart-toast-icon" class="bi" aria-hidden="true"></i>
                <span id="cart-toast-msg"></span>
            </div>
            <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
    </div>
</div>

<script>
window.__APP__ = window.__APP__ || {};
window.__APP__.isLoggedIn = <?= isLoggedIn() ? 'true' : 'false' ?>;
window.__APP__.csrfToken = '<?= e($csrf) ?>';
window.__APP__.siteUrl = '<?= e(SITE_URL) ?>';
window.__APP__.geminiChatEnabled = <?= (defined('ENABLE_GEMINI_CHATBOT') && ENABLE_GEMINI_CHATBOT) ? 'true' : 'false' ?>;
</script>

<!-- Bootstrap 5 JS Bundle -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>

<!-- Custom JS -->
<script src="<?= SITE_URL ?>/assets/js/main.js"></script>

<!-- Add to Cart AJAX + Toast -->
<script>
(function () {
    function showToast(message, success) {
        const toastEl  = document.getElementById('cart-toast');
        const msgEl    = document.getElementById('cart-toast-msg');
        const iconEl   = document.getElementById('cart-toast-icon');

        msgEl.textContent = message;

        if (success) {
            toastEl.className = 'toast align-items-center border-0 text-bg-success';
            iconEl.className  = 'bi bi-cart-check-fill';
        } else {
            toastEl.className = 'toast align-items-center border-0 text-bg-danger';
            iconEl.className  = 'bi bi-exclamation-circle-fill';
        }

        const toast = bootstrap.Toast.getOrCreateInstance(toastEl, { delay: 3000 });
        toast.show();
    }

    function updateCartBadge(count) {
        const badge = document.getElementById('cart-badge');
        if (!badge) return;
        badge.textContent = count;
        badge.style.display = count > 0 ? '' : 'none';
    }

    // Intercept any "Add to Cart" form submission (action=add)
    document.addEventListener('submit', function (e) {
        const form = e.target;

        // Only intercept forms that POST action=add to cart_action.php
        const actionInput = form.querySelector('input[name="action"]');
        if (!actionInput || actionInput.value !== 'add') return;

        e.preventDefault();

        const data = new FormData(form);

        fetch(window.__APP__.siteUrl + '/pages/cart_action.php', {
            method: 'POST',
            headers: { 'X-Requested-With': 'XMLHttpRequest' },
            body: data,
        })
        .then(function (res) { return res.json(); })
        .then(function (json) {
            showToast(json.message, json.success);
            if (json.success && json.cart_count !== undefined) {
                updateCartBadge(json.cart_count);
            }
        })
        .catch(function () {
            showToast('Something went wrong. Please try again.', false);
        });
    });
})();
</script>

</body>
</html>